FROM ubuntu:20.04

USER root

RUN apt-get update -y && \
    apt-get install -y python3 python3-pip git

RUN pip3 install watchdog argh PyYAML boto3 requests

WORKDIR /tmp

RUN git clone https://github.com/aws/aws-iot-device-sdk-python.git
WORKDIR /tmp/aws-iot-device-sdk-python
RUN pip3 install .
## requirements for your python package
## moronic aws engineers have created a setup.py
## that depends on the to-be-installed package modules themselves
## so we have to copy this:
#ADD aws-iot-device-sdk-python /tmp/aws-iot-device-sdk-python
#WORKDIR /tmp/aws-iot-device-sdk-python
## the aws-boys are using "from distutils.core import setup"
## instead of "from setuptools import setup", so this won't work..?
# RUN python3 setup.py egg_info
# RUN pip3 install -r *.egg-info/requires.txt
## ..but they seem to have no dependencies, so no need to copy in the first place
